// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYJViTc_LSI7o8YkvifL1J3CLz0znOzo',
    appId: '1:1057901430323:web:420516f750f615fd698546',
    messagingSenderId: '1057901430323',
    projectId: 'chat-64dd5',
    authDomain: 'chat-64dd5.firebaseapp.com',
    storageBucket: 'chat-64dd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzqzewMaV0lStdMSEupCZO0C8bGyOzc8',
    appId: '1:1057901430323:android:89451e5065fe1998698546',
    messagingSenderId: '1057901430323',
    projectId: 'chat-64dd5',
    storageBucket: 'chat-64dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY8QV7sSMyVx1Lqeisa-h0QkwEXJaQl7U',
    appId: '1:1057901430323:ios:d4da1b611e68340c698546',
    messagingSenderId: '1057901430323',
    projectId: 'chat-64dd5',
    storageBucket: 'chat-64dd5.appspot.com',
    androidClientId: '1057901430323-7rquu5t09saepq3edk1h0lmb5m1i2ptp.apps.googleusercontent.com',
    iosClientId: '1057901430323-3soqu94ov47vkcb9rpj1udd7435iqb6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
